title: Beatrice Lowman
description: |
  <img src="IMG_1663.JPG" alt="Beatrice Lowman" style="width:160px; border-radius:8px; margin-top:10px;">
  <br>
  <a href="https://github.com/bealowman">View My GitHub Profile</a>
theme: jekyll-theme-minimal
